<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit3292de0ffa7c474693e087220940bf89
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Stripe\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Stripe\\' => 
        array (
            0 => __DIR__ . '/..' . '/stripe/stripe-php/lib',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit3292de0ffa7c474693e087220940bf89::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit3292de0ffa7c474693e087220940bf89::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
